### ISSUE TITLE
OASP4J Installer

### ISSUE THREAD

**Issue by themetalone** [themetalone/oomph-fork#2]
### TODO
- [x] Disable Launch automatically
- [ ] Remove Launch automatically
- [x] Include OASP4J
- [ ] Disable all other catalogues as default
- [ ] Include OASP4J plugins
